<?php
/** Fresh isolated Stage 2 suite followed by existing Registrar enrollment/student login. */
require __DIR__ . '/stage2-http.php';
$beforeChecks = $checks;
$beforeStudents = (int)$db->query('SELECT COUNT(*) FROM students')->fetchColumn();
$beforeEnrollment = (int)$db->query('SELECT COUNT(*) FROM student_enrollment')->fetchColumn();
$beforeMessages = count(file('/runtime/messages.jsonl', FILE_IGNORE_NEW_LINES));
$beforeHistory = countHistory($id);
$beforeOutbox = outbox($id);
ok(applicant($id)['first_name'] === 'STAGE2_TEST' && applicant($id)['status'] === 'PAYMENT_VERIFIED', 'Enrollment fixture must be synthetic and verified');
$detail = "Modules.php?modname=$review&applicant_id=$id";
[, $html] = http($registrar, $detail);
$finalFields = ['token' => field($html, 'token'), 'abugida_csrf' => field($html, 'abugida_csrf')];
http($registrar, $detail . '&modfunc=final_confirm', array_replace($finalFields, ['abugida_csrf' => 'invalid']));
ok(applicant($id)['status'] === 'PAYMENT_VERIFIED' && (int)$db->query('SELECT COUNT(*) FROM students')->fetchColumn() === $beforeStudents, 'Invalid CSRF created permanent records');
http($finance, $detail . '&modfunc=final_confirm', $finalFields);
ok(applicant($id)['status'] === 'PAYMENT_VERIFIED', 'Finance finalized Registrar enrollment');
[$status] = http($registrar, $detail . '&modfunc=final_confirm', $finalFields);
ok($status === 200 || $status === 302, 'Final enrollment HTTP failure');
$active = applicant($id);
ok($active['status'] === 'ACTIVE' && (int)$active['student_id'] > 0 && $active['generated_username'] !== '', 'Permanent student account not linked to ACTIVE applicant');
$q = $db->prepare('SELECT * FROM students WHERE student_id=?'); $q->execute([$active['student_id']]); $student = $q->fetch(PDO::FETCH_ASSOC);
ok($student && $student['username'] === $active['generated_username'] && $student['first_name'] === 'STAGE2_TEST' && $student['last_name'] === $active['last_name'], 'Student identity/username mismatch');
$q = $db->prepare('SELECT * FROM student_enrollment WHERE student_id=?'); $q->execute([$active['student_id']]); $enrolled = $q->fetchAll(PDO::FETCH_ASSOC);
ok(count($enrolled) === 1 && (int)$enrolled[0]['syear'] === 2026 && (int)$enrolled[0]['school_id'] === 1 && $enrolled[0]['end_date'] === null, 'Current active enrollment missing');
$q = $db->prepare('SELECT title,short_name FROM school_gradelevels WHERE id=?'); $q->execute([$enrolled[0]['grade_id']]); $grade = $q->fetch(PDO::FETCH_ASSOC);
ok($grade && preg_match('/(^|[^0-9])7([^0-9]|$)/', $grade['title'] . ' ' . $grade['short_name']), 'Grade mapping incorrect');
ok(countHistory($id) === $beforeHistory + 1 && outbox($id) === $beforeOutbox, 'Final audit missing or prior outbox changed');
$messages = array_map(fn($line) => json_decode($line, true), file('/runtime/messages.jsonl', FILE_IGNORE_NEW_LINES));
ok(count($messages) === $beforeMessages + 1, 'Expected exactly one credentials email');
$credentialsMail = end($messages); $credentialsBody = quoted_printable_decode($credentialsMail['message']);
ok($credentialsMail['tls'] && $credentialsMail['authenticated'] && str_contains($credentialsBody, 'Abugida SIS account created') && str_contains($credentialsBody, 'Username: ' . $active['generated_username']), 'Credentials email content/transport incorrect');
ok(preg_match('/Temporary password: ([^\r\n]+)/', $credentialsBody, $match) === 1, 'Credentials email missing temporary password');
$temporaryPassword = trim($match[1]);
ok($student['password'] !== $temporaryPassword && hash_equals($student['password'], crypt($temporaryPassword, $student['password'])), 'Generated password is not stored as a valid hash');
http($registrar, $detail . '&modfunc=final_confirm', $finalFields);
http($registrar, $detail);
ok((int)$db->query('SELECT COUNT(*) FROM students')->fetchColumn() === $beforeStudents + 1 && (int)$db->query('SELECT COUNT(*) FROM student_enrollment')->fetchColumn() === $beforeEnrollment + 1 && countHistory($id) === $beforeHistory + 1, 'Duplicate confirmation created permanent records/history');
ok(count(file('/runtime/messages.jsonl', FILE_IGNORE_NEW_LINES)) === count($messages), 'Duplicate confirmation resent credentials');
$studentJar = []; http($studentJar, 'index.php');
http($studentJar, 'index.php', ['USERNAME' => $active['generated_username'], 'PASSWORD' => $temporaryPassword]);
[, $portal] = http($studentJar, 'Modules.php?modname=Students/Student.php');
ok(str_contains($portal, 'STAGE2_TEST') && str_contains($portal, $active['last_name']) && !str_contains($portal, 'Incorrect username or password.'), 'Default student portal did not show the enrolled student');
$q = $db->prepare('SELECT last_login FROM students WHERE student_id=?'); $q->execute([$active['student_id']]);
ok($q->fetchColumn() !== null, 'Generated student login did not update LAST_LOGIN');
echo 'PASS ' . ($checks - $beforeChecks) . " final-enrollment/credentials/default-portal checks; generated credentials retained only in ignored SMTP fixture logs.\n";
